version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11.3-node
    steps:
      - checkout
      - run:
          name: install jupyterlab
          command: python -m pip install jupyterlab
      - run:
          name: test jupyterlab installation
          command: jupyter nbconvert --version
      - run:
          name: install yarn dependencies
          command: yarn install
      - run:
          name: build app
          command: yarn build
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  build-workflow:
    jobs:
      - build
